# Generated by Django 4.2.2 on 2023-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
