# Generated by Django 4.2.2 on 2023-06-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_services', '0003_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TripGroup',
        ),
    ]
