# Generated by Django 4.2.2 on 2023-06-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_bus_ticket_service_user_apartment_service_and_more'),
        ('ticket_services', '0006_trip_trip_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.reception'),
        ),
        migrations.AddField(
            model_name='trip',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
    ]
