# Generated by Django 4.2.2 on 2023-06-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_services', '0007_seat_belongs_to_ticket_belongs_to_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='ticket_number',
            new_name='trip_number',
        ),
    ]
