# Generated by Django 4.2.2 on 2023-06-11 18:52

from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdisplayimages',
            name='display_images',
            field=models.ImageField(null=True, upload_to=hotels.models.room_display_images_upload_path),
        ),
    ]
