# Generated by Django 4.2.2 on 2023-06-11 19:10

from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roomdisplayimages_display_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=hotels.models.room_images_upload_path),
        ),
    ]
