# Generated by Django 4.2.2 on 2023-06-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reception'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_apartment',
            new_name='use_apartment',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_company',
            new_name='use_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_hotel',
            new_name='use_hotel',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_restaurant',
            new_name='use_restaurant',
        ),
    ]
