# Generated by Django 4.2.2 on 2023-06-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Vendor',
        ),
    ]
