# Generated by Django 4.2.2 on 2023-06-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_office',
            field=models.BooleanField(default=False),
        ),
    ]
