# Generated by Django 4.2.2 on 2023-06-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_company',
            new_name='use_visitor',
        ),
    ]
