# Generated by Django 4.2.2 on 2023-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_use_company_user_use_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bus_ticketing_service',
            field=models.BooleanField(default=False),
        ),
    ]
