# Generated by Django 4.2.2 on 2023-06-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_bus_ticketing_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bus_ticketing_service',
            new_name='bus_ticket_service',
        ),
    ]
