# Generated by Django 4.2.2 on 2023-06-16 19:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_bus_ticketing_service_user_bus_ticket_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=accounts.models.profile_images_upload_path),
        ),
    ]
