# Generated by Django 4.2.2 on 2023-06-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profiledisplayimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='route_slug',
            field=models.SlugField(null=True),
        ),
    ]
