# Generated by Django 4.2.2 on 2023-06-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_route_slug_user_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bus_ticket_service',
            new_name='apartment_service',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='use_apartment',
            new_name='hotel_service',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='use_hotel',
            new_name='restaurant_service',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='use_restaurant',
            new_name='ticket_service',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='use_visitor',
            new_name='visitor_check',
        ),
    ]
