# Generated by Django 4.2.2 on 2023-06-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='created_by',
            new_name='vendor',
        ),
    ]
