# Generated by Django 4.2.2 on 2023-06-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_rename_created_by_visitor_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
