# Generated by Django 4.2.2 on 2023-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_checked_in_visitor_checked_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='id_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
