# Generated by Django 4.2.2 on 2023-06-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_visitor_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='id_number',
        ),
    ]
