# Generated by Django 4.2.2 on 2023-06-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_remove_visitor_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date_visited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='out_time',
            field=models.TimeField(null=True),
        ),
    ]
