# Generated by Django 4.2.2 on 2023-06-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_visitor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='image',
            new_name='visitor_image',
        ),
    ]
